### ISSUE TITLE
docker image seems not to be working properly

### ISSUE THREAD

**Issue by danielzzz** [nevinpuri/erlog#2]
hello, I am getting this error:
![image](https://user-images.githubusercontent.com/351916/219874216-b1540c48-372e-4c4c-9ae6-50c3203ab644.png)

this is my docker-compose file:
````
version: '3'

services:
    erlog:
        image: nevin1901/erlog:latest
        restart: "no"
        ports:
          - '8086:8080'
          ```
          
         best, dan
